name: CI GNU/Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set executable permission for Premake
        run: chmod +x vendor/premake/bin/premake5_linux

      - name: Set up dependencies on Ubuntu
        run: sudo apt-get install -y build-essential

      - name: Set configuration as lowercase
        run: echo "CONFIGURATION=${{ matrix.configuration == 'Debug' && 'debug' || 'release' }}" >> $GITHUB_ENV

      - name: Build with Premake
        run: |
          vendor/premake/bin/premake5_linux gmake2
          cd MyProject
          make config=$CONFIGURATION -j$(nproc)  # Use $CONFIGURATION (lowercase)

      - name: Run tests
        run: ./bin/${{ matrix.configuration }}-linux-x86_64/MyProjectTests
